### ISSUE TITLE
Improve Training data simulation

### ISSUE THREAD

**Issue by gwarmstrong** [gwarmstrong/mohawk#29]
Some ideas of things that can/should be done
- [ ] ensure that reads are sample from the same location only once #27
- [ ] Add simulated errors to training data (could involve neural network) #1
- [ ] Add error correction module to fix low-quality sequences (could use some real data with alignments to genome?) #28
